# Site settings
title: lab.guchanalkan.com
email: zehreken@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Experiments about programming, tips about game development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://guchanalkan.com" # the base hostname & protocol for your site
twitter_username: zehreken
github_username:  zehreken

# Build settings
markdown: kramdown
